package main

import (
	"log/slog"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ethpandaops/ogen-mcp/internal/mapper"
)

func TestRunGeneratesCode(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	input := filepath.Join(dir, "spec.yaml")
	output := filepath.Join(dir, "generated.go")

	spec := `
openapi: "3.1.0"
info:
  title: Minimal31
  version: "1.0.0"
paths:
  /health:
    get:
      operationId: healthCheck
      responses:
        "200":
          description: OK
`
	require.NoError(t, os.WriteFile(input, []byte(spec), 0o600))

	err := run(slog.New(slog.DiscardHandler), input, output, mapper.MapOptions{
		PackageName: "mcpserver",
	})
	require.NoError(t, err)

	// #nosec G304 -- output is a file in t.TempDir controlled by the test.
	got, readErr := os.ReadFile(output)
	require.NoError(t, readErr)
	assert.Contains(t, string(got), "Code generated by ogen-mcp")
	assert.Contains(t, string(got), "package mcpserver")
}

func TestRunFailsOnOpenAPI31NullableTypeArray(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	input := filepath.Join(dir, "spec.yaml")
	output := filepath.Join(dir, "generated.go")

	spec := `
openapi: "3.1.0"
info:
  title: UnsupportedNullable31
  version: "1.0.0"
paths:
  /thing:
    get:
      operationId: getThing
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  maybe:
                    type: ["string", "null"]
`
	require.NoError(t, os.WriteFile(input, []byte(spec), 0o600))

	err := run(slog.New(slog.DiscardHandler), input, output, mapper.MapOptions{
		PackageName: "mcpserver",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "openapi 3.1 schema compatibility")
	assert.Contains(t, err.Error(), "oneOf")
}
