// Code generated by ogen-mcp. DO NOT EDIT.
package mcpserver

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Search domain constants.
const (
	SearchDomainListOrders  = "list_orders"
	SearchDomainListPets    = "list_pets"
	SearchDomainShowPetByID = "show_pet_by_id"
)

// Execute action constants.
const (
	ExecuteActionTagPet      = "tag_pet"
	ExecuteActionCreateOrder = "create_order"
	ExecuteActionCreatePet   = "create_pet"
	ExecuteActionDeletePet   = "delete_pet"
	ExecuteActionUpdatePet   = "update_pet"
)

// Handler defines the interface for MCP tool call handlers.
type Handler interface {
	// SearchListOrders handles the "list_orders" search domain.
	// GET /orders — List all orders
	// Params: limit (query, any, optional)
	SearchListOrders(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// SearchListPets handles the "list_pets" search domain.
	// GET /pets — List all pets
	// Params: status (query, any, optional), limit (query, any, optional)
	SearchListPets(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// SearchShowPetByID handles the "show_pet_by_id" search domain.
	// GET /pets/{petId} — Get a pet by ID
	// Params: petId (path, int64, required)
	SearchShowPetByID(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// ExecuteTagPet handles the "tag_pet" execute action.
	// POST /pets/{petId}/tags — Add a tag to a pet
	// Params: petId (path, int64, required)
	// Body: required
	ExecuteTagPet(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// ExecuteCreateOrder handles the "create_order" execute action.
	// POST /orders — Create an order
	// Body: required
	ExecuteCreateOrder(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// ExecuteCreatePet handles the "create_pet" execute action.
	// POST /pets — Create a pet
	// Body: required
	ExecuteCreatePet(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// ExecuteDeletePet handles the "delete_pet" execute action.
	// DELETE /pets/{petId} — Delete a pet
	// Params: petId (path, int64, required)
	ExecuteDeletePet(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)

	// ExecuteUpdatePet handles the "update_pet" execute action.
	// PUT /pets/{petId} — Update a pet
	// Params: petId (path, int64, required)
	// Body: required
	ExecuteUpdatePet(ctx context.Context, params json.RawMessage) (*mcp.CallToolResult, error)
}

// RegisterTools registers search and execute tools with the MCP server.
func RegisterTools(srv *mcp.Server, handler Handler) {
	h := &generatedHandler{handler: handler}

	srv.AddTool(&mcp.Tool{
		Name:        "search",
		Title:       "Search",
		Description: searchDescription,
		InputSchema: searchInputSchema(),
		Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true},
	}, h.handleSearch)

	srv.AddTool(&mcp.Tool{
		Name:        "execute",
		Title:       "Execute",
		Description: executeDescription,
		InputSchema: executeInputSchema(),
		Annotations: &mcp.ToolAnnotations{DestructiveHint: new(true)},
	}, h.handleExecute)
}

type generatedHandler struct {
	handler Handler
}

const searchDescription = "Search and discover:\n" +
	"- list_orders: List all orders (limit)\n" +
	"- list_pets: List all pets (status, limit)\n" +
	"- show_pet_by_id: Get a pet by ID (petId)\n" +
	""

const executeDescription = "Execute actions:\n" +
	"- tag_pet: Add a tag to a pet (petId, body)\n" +
	"- create_order: Create an order (body)\n" +
	"- create_pet: Create a pet (body)\n" +
	"- delete_pet: Delete a pet (petId)\n" +
	"- update_pet: Update a pet (petId, body)\n" +
	""

func searchInputSchema() any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"domain": map[string]any{
				"type":        "string",
				"description": "The search domain to query.",
				"enum":        []string{SearchDomainListOrders, SearchDomainListPets, SearchDomainShowPetByID},
			},
			"params": map[string]any{
				"type":        "object",
				"description": "Parameters for the search domain. See tool description for accepted params per domain.",
			},
		},
		"required":             []string{"domain"},
		"additionalProperties": false,
	}
}

func executeInputSchema() any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "The action to execute.",
				"enum":        []string{ExecuteActionTagPet, ExecuteActionCreateOrder, ExecuteActionCreatePet, ExecuteActionDeletePet, ExecuteActionUpdatePet},
			},
			"params": map[string]any{
				"type":        "object",
				"description": "Parameters for the action. See tool description for accepted params per action.",
			},
		},
		"required":             []string{"action"},
		"additionalProperties": false,
	}
}

func (h *generatedHandler) handleSearch(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	var args struct {
		Domain string          `json:"domain"`
		Params json.RawMessage `json:"params"`
	}

	if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
		return nil, fmt.Errorf("invalid search arguments: %w", err)
	}

	switch args.Domain {
	case SearchDomainListOrders:
		return h.handler.SearchListOrders(ctx, args.Params)
	case SearchDomainListPets:
		return h.handler.SearchListPets(ctx, args.Params)
	case SearchDomainShowPetByID:
		return h.handler.SearchShowPetByID(ctx, args.Params)
	default:
		available := []string{SearchDomainListOrders, SearchDomainListPets, SearchDomainShowPetByID}
		return nil, fmt.Errorf("unknown search domain: %q, available: [%s]", args.Domain, strings.Join(available, ", "))
	}
}

func (h *generatedHandler) handleExecute(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	var args struct {
		Action string          `json:"action"`
		Params json.RawMessage `json:"params"`
	}

	if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
		return nil, fmt.Errorf("invalid execute arguments: %w", err)
	}

	switch args.Action {
	case ExecuteActionTagPet:
		return h.handler.ExecuteTagPet(ctx, args.Params)
	case ExecuteActionCreateOrder:
		return h.handler.ExecuteCreateOrder(ctx, args.Params)
	case ExecuteActionCreatePet:
		return h.handler.ExecuteCreatePet(ctx, args.Params)
	case ExecuteActionDeletePet:
		return h.handler.ExecuteDeletePet(ctx, args.Params)
	case ExecuteActionUpdatePet:
		return h.handler.ExecuteUpdatePet(ctx, args.Params)
	default:
		available := []string{ExecuteActionTagPet, ExecuteActionCreateOrder, ExecuteActionCreatePet, ExecuteActionDeletePet, ExecuteActionUpdatePet}
		return nil, fmt.Errorf("unknown execute action: %q, available: [%s]", args.Action, strings.Join(available, ", "))
	}
}

// schemaContents maps schema names to their compact JSON Schema definitions.
var schemaContents = map[string]string{
	"CreateOrderRequest": `{"type":"object","properties":{"petId":{"type":"integer","format":"int64"},"quantity":{"type":"integer","format":"int32"}},"required":["petId"]}`,
	"CreatePetRequest":   `{"type":"object","properties":{"name":{"type":"string"},"status":{"type":"string","enum":["available","pending","sold"]}},"required":["name"]}`,
	"Order":              `{"type":"object","properties":{"id":{"type":"integer","format":"int64"},"petId":{"type":"integer","format":"int64"},"quantity":{"type":"integer","format":"int32"}},"required":["id","petId"]}`,
	"Pet":                `{"type":"object","properties":{"id":{"type":"integer","format":"int64"},"name":{"type":"string"},"status":{"type":"string","enum":["available","pending","sold"]},"tags":{"type":"array","items":{"type":"string"}}},"required":["id","name"]}`,
}

// RegisterResources registers schema resources with the MCP server.
func RegisterResources(srv *mcp.Server) {
	srv.AddResource(&mcp.Resource{
		URI:         "openapi://schemas",
		Name:        "schemas",
		Title:       "API Schemas",
		Description: "List all API schemas: " + schemaNamesList(),
		MIMEType:    "application/json",
	}, handleSchemaList)

	srv.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "openapi://schemas/{name}",
		Name:        "schema",
		Title:       "API Schema",
		Description: "Get a specific API schema definition by name",
		MIMEType:    "application/json",
	}, handleSchemaRead)
}

func schemaNamesList() string {
	names := make([]string, 0, len(schemaContents))
	for name := range schemaContents {
		names = append(names, name)
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}

func handleSchemaList(_ context.Context, _ *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
	type entry struct {
		Name        string `json:"name"`
		Description string `json:"description,omitempty"`
	}

	entries := make([]entry, 0, len(schemaContents))
	entries = append(entries, entry{Name: "CreateOrderRequest", Description: ""})
	entries = append(entries, entry{Name: "CreatePetRequest", Description: ""})
	entries = append(entries, entry{Name: "Order", Description: ""})
	entries = append(entries, entry{Name: "Pet", Description: ""})

	data, err := json.Marshal(entries)
	if err != nil {
		return nil, fmt.Errorf("marshaling schema list: %w", err)
	}

	rc := &mcp.ResourceContents{
		URI:      "openapi://schemas",
		MIMEType: "application/json",
		Text:     string(data),
	}

	return &mcp.ReadResourceResult{
		Contents: []*mcp.ResourceContents{rc},
	}, nil
}

func handleSchemaRead(_ context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
	uri := req.Params.URI
	const prefix = "openapi://schemas/"
	if !strings.HasPrefix(uri, prefix) {
		return nil, mcp.ResourceNotFoundError(uri)
	}

	name := strings.TrimPrefix(uri, prefix)

	content, ok := schemaContents[name]
	if !ok {
		return nil, mcp.ResourceNotFoundError(uri)
	}

	rc := &mcp.ResourceContents{
		URI:      uri,
		MIMEType: "application/json",
		Text:     content,
	}

	return &mcp.ReadResourceResult{
		Contents: []*mcp.ResourceContents{rc},
	}, nil
}
